//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1MySqlEFADOnet
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.city = new HashSet<city>();
            this.countrylanguage = new HashSet<countrylanguage>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string Continent { get; set; }
        public string Region { get; set; }
        public float SurfaceArea { get; set; }
        public Nullable<short> IndepYear { get; set; }
        public int Population { get; set; }
        public Nullable<float> LifeExpectancy { get; set; }
        public Nullable<float> GNP { get; set; }
        public Nullable<float> GNPOld { get; set; }
        public string LocalName { get; set; }
        public string GovernmentForm { get; set; }
        public string HeadOfState { get; set; }
        public Nullable<int> Capital { get; set; }
        public string Code2 { get; set; }
    
        public virtual ICollection<city> city { get; set; }
        public virtual ICollection<countrylanguage> countrylanguage { get; set; }
    }
}
