// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSCAR.Models;

#nullable disable

namespace WebApiSCAR.Migrations
{
    [DbContext(typeof(SCARContext))]
    partial class SCARContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApiSCAR.Models.BitacoraRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("InvitadoId")
                        .HasColumnType("int");

                    b.Property<int?>("ResidenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitadoId");

                    b.HasIndex("ResidenteId");

                    b.ToTable("BitacorasRegistro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaHoraEntrada = new DateTime(2025, 7, 4, 1, 30, 38, 350, DateTimeKind.Local).AddTicks(234),
                            FechaHoraSalida = new DateTime(2025, 7, 4, 2, 30, 38, 350, DateTimeKind.Local).AddTicks(685),
                            ResidenteId = 1
                        },
                        new
                        {
                            Id = 2,
                            FechaHoraEntrada = new DateTime(2025, 7, 4, 3, 30, 38, 350, DateTimeKind.Local).AddTicks(1736),
                            FechaHoraSalida = new DateTime(2025, 7, 4, 4, 30, 38, 350, DateTimeKind.Local).AddTicks(1739),
                            ResidenteId = 2
                        },
                        new
                        {
                            Id = 3,
                            FechaHoraEntrada = new DateTime(2025, 7, 4, 5, 30, 38, 350, DateTimeKind.Local).AddTicks(1743),
                            ResidenteId = 3
                        },
                        new
                        {
                            Id = 4,
                            FechaHoraEntrada = new DateTime(2025, 7, 4, 0, 30, 38, 350, DateTimeKind.Local).AddTicks(1746),
                            FechaHoraSalida = new DateTime(2025, 7, 4, 1, 30, 38, 350, DateTimeKind.Local).AddTicks(1747),
                            InvitadoId = 1
                        },
                        new
                        {
                            Id = 5,
                            FechaHoraEntrada = new DateTime(2025, 7, 3, 23, 30, 38, 350, DateTimeKind.Local).AddTicks(1750),
                            FechaHoraSalida = new DateTime(2025, 7, 4, 0, 30, 38, 350, DateTimeKind.Local).AddTicks(1752),
                            InvitadoId = 2
                        });
                });

            modelBuilder.Entity("WebApiSCAR.Models.Invitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResidenteId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidenteId");

                    b.ToTable("Invitados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Ap1",
                            Email = "inv1@mail.com",
                            FechaVisita = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(8103),
                            Nombre = "Inv1",
                            ResidenteId = 1,
                            Telefono = "1000001",
                            Token = "token1"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Ap2",
                            Email = "inv2@mail.com",
                            FechaVisita = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(8941),
                            Nombre = "Inv2",
                            ResidenteId = 2,
                            Telefono = "1000002",
                            Token = "token2"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Ap3",
                            Email = "inv3@mail.com",
                            FechaVisita = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(8945),
                            Nombre = "Inv3",
                            ResidenteId = 3,
                            Telefono = "1000003",
                            Token = "token3"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Ap4",
                            Email = "inv4@mail.com",
                            FechaVisita = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(8949),
                            Nombre = "Inv4",
                            ResidenteId = 4,
                            Telefono = "1000004",
                            Token = "token4"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Ap5",
                            Email = "inv5@mail.com",
                            FechaVisita = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(8952),
                            Nombre = "Inv5",
                            ResidenteId = 5,
                            Telefono = "1000005",
                            Token = "token5"
                        });
                });

            modelBuilder.Entity("WebApiSCAR.Models.Residente", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Residentes");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Apellido = "Pérez",
                            Direccion = "Calle 1",
                            Email = "juan1@mail.com",
                            FechaNacimiento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 7, 4, 6, 30, 38, 346, DateTimeKind.Local).AddTicks(9586),
                            Nombre = "Juan",
                            Telefono = "1111111"
                        },
                        new
                        {
                            UserId = 2,
                            Apellido = "García",
                            Direccion = "Calle 2",
                            Email = "ana2@mail.com",
                            FechaNacimiento = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(4793),
                            Nombre = "Ana",
                            Telefono = "2222222"
                        },
                        new
                        {
                            UserId = 3,
                            Apellido = "Martínez",
                            Direccion = "Calle 3",
                            Email = "luis3@mail.com",
                            FechaNacimiento = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(4813),
                            Nombre = "Luis",
                            Telefono = "3333333"
                        },
                        new
                        {
                            UserId = 4,
                            Apellido = "López",
                            Direccion = "Calle 4",
                            Email = "sofia4@mail.com",
                            FechaNacimiento = new DateTime(1993, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(4817),
                            Nombre = "Sofía",
                            Telefono = "4444444"
                        },
                        new
                        {
                            UserId = 5,
                            Apellido = "Ruiz",
                            Direccion = "Calle 5",
                            Email = "carlos5@mail.com",
                            FechaNacimiento = new DateTime(1994, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2025, 7, 4, 6, 30, 38, 349, DateTimeKind.Local).AddTicks(4820),
                            Nombre = "Carlos",
                            Telefono = "5555555"
                        });
                });

            modelBuilder.Entity("WebApiSCAR.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "pass1",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "pass2",
                            Username = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "pass3",
                            Username = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "pass4",
                            Username = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "pass5",
                            Username = "user5"
                        });
                });

            modelBuilder.Entity("WebApiSCAR.Models.BitacoraRegistro", b =>
                {
                    b.HasOne("WebApiSCAR.Models.Invitado", "Invitado")
                        .WithMany()
                        .HasForeignKey("InvitadoId");

                    b.HasOne("WebApiSCAR.Models.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId");

                    b.Navigation("Invitado");

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("WebApiSCAR.Models.Invitado", b =>
                {
                    b.HasOne("WebApiSCAR.Models.Residente", "Residente")
                        .WithMany()
                        .HasForeignKey("ResidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residente");
                });

            modelBuilder.Entity("WebApiSCAR.Models.Residente", b =>
                {
                    b.HasOne("WebApiSCAR.Models.User", "User")
                        .WithOne("Residente")
                        .HasForeignKey("WebApiSCAR.Models.Residente", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiSCAR.Models.User", b =>
                {
                    b.Navigation("Residente");
                });
#pragma warning restore 612, 618
        }
    }
}
